module.exports.mr = {
  object_kind: "merge_request",
  user: {
    name: "Administrator",
    username: "root",
    avatar_url: "http://www.gravatar.com/avatar/e64c7d89f26bd1972efa854d13d7dd61?s=40\u0026d=identicon",
  },
  object_attributes: {
    id: 99,
    target_branch: "master",
    source_branch: "ms-viewport",
    source_project_id: 14,
    author_id: 51,
    assignee_id: 6,
    title: "MS-Viewport",
    created_at: "2013-12-03T17:23:34Z",
    updated_at: "2013-12-03T17:23:34Z",
    st_commits: null,
    st_diffs: null,
    milestone_id: null,
    state: "opened",
    merge_status: "unchecked",
    target_project_id: 14,
    iid: 1,
    description: "",
    source: {
      name: "Awesome Project",
      description: "Aut reprehenderit ut est.",
      web_url: "http://example.com/awesome_space/awesome_project",
      avatar_url: null,
      git_ssh_url: "git@example.com:awesome_space/awesome_project.git",
      git_http_url: "http://example.com/awesome_space/awesome_project.git",
      namespace: "Awesome Space",
      visibility_level: 20,
      path_with_namespace: "awesome_space/awesome_project",
      default_branch: "master",
      homepage: "http://example.com/awesome_space/awesome_project",
      url: "http://example.com/awesome_space/awesome_project.git",
      ssh_url: "git@example.com:awesome_space/awesome_project.git",
      http_url: "http://example.com/awesome_space/awesome_project.git",
    },
    target: {
      name: "Awesome Project",
      description: "Aut reprehenderit ut est.",
      web_url: "http://example.com/awesome_space/awesome_project",
      avatar_url: null,
      git_ssh_url: "git@example.com:awesome_space/awesome_project.git",
      git_http_url: "http://example.com/awesome_space/awesome_project.git",
      namespace: "Awesome Space",
      visibility_level: 20,
      path_with_namespace: "awesome_space/awesome_project",
      default_branch: "master",
      homepage: "http://example.com/awesome_space/awesome_project",
      url: "http://example.com/awesome_space/awesome_project.git",
      ssh_url: "git@example.com:awesome_space/awesome_project.git",
      http_url: "http://example.com/awesome_space/awesome_project.git",
    },
    last_commit: {
      id: "da1560886d4f094c3e6c9ef40349f7d38b5d27d7",
      message: "fixed readme",
      timestamp: "2012-01-03T23:36:29+02:00",
      url: "http://example.com/awesome_space/awesome_project/commits/da1560886d4f094c3e6c9ef40349f7d38b5d27d7",
      author: {
        name: "GitLab dev user",
        email: "gitlabdev@dv6700.(none)",
      },
    },
    work_in_progress: false,
    url: "http://example.com/diaspora/merge_requests/1",
    action: "open",
    assignee: {
      name: "User1",
      username: "user1",
      avatar_url: "http://www.gravatar.com/avatar/e64c7d89f26bd1972efa854d13d7dd61?s=40\u0026d=identicon",
    },
  },
};
module.exports.issue = {
  object_kind: "issue",
  user: {
    name: "Administrator",
    username: "root",
    avatar_url: "http://www.gravatar.com/avatar/e64c7d89f26bd1972efa854d13d7dd61?s=40\u0026d=identicon",
  },
  project: {
    name: "Gitlab Test",
    description: "Aut reprehenderit ut est.",
    web_url: "http://example.com/gitlabhq/gitlab-test",
    avatar_url: null,
    git_ssh_url: "git@example.com:gitlabhq/gitlab-test.git",
    git_http_url: "http://example.com/gitlabhq/gitlab-test.git",
    namespace: "GitlabHQ",
    visibility_level: 20,
    path_with_namespace: "gitlabhq/gitlab-test",
    default_branch: "master",
    homepage: "http://example.com/gitlabhq/gitlab-test",
    url: "http://example.com/gitlabhq/gitlab-test.git",
    ssh_url: "git@example.com:gitlabhq/gitlab-test.git",
    http_url: "http://example.com/gitlabhq/gitlab-test.git",
  },
  repository: {
    name: "Gitlab Test",
    url: "http://example.com/gitlabhq/gitlab-test.git",
    description: "Aut reprehenderit ut est.",
    homepage: "http://example.com/gitlabhq/gitlab-test",
  },
  object_attributes: {
    id: 301,
    title: "New API: create/update/delete file",
    assignee_id: 51,
    author_id: 51,
    project_id: 14,
    created_at: "2013-12-03T17:15:43Z",
    updated_at: "2013-12-03T17:15:43Z",
    position: 0,
    branch_name: null,
    description: "Create new API for manipulations with repository",
    milestone_id: null,
    state: "opened",
    iid: 23,
    url: "http://example.com/diaspora/issues/23",
    action: "open",
  },
  assignee: {
    name: "User1",
    username: "user1",
    avatar_url: "http://www.gravatar.com/avatar/e64c7d89f26bd1972efa854d13d7dd61?s=40\u0026d=identicon",
  },
};
module.exports.tag = {
  object_kind: "tag_push",
  before: "0000000000000000000000000000000000000000",
  after: "82b3d5ae55f7080f1e6022629cdb57bfae7cccc7",
  ref: "refs/tags/v1.0.0",
  checkout_sha: "82b3d5ae55f7080f1e6022629cdb57bfae7cccc7",
  user_id: 1,
  user_name: "John Smith",
  user_avatar:
    "https://s.gravatar.com/avatar/d4c74594d841139328695756648b6bd6?s=8://s.gravatar.com/avatar/d4c74594d841139328695756648b6bd6?s=80",
  project_id: 1,
  project: {
    name: "Example",
    description: "",
    web_url: "http://example.com/jsmith/example",
    avatar_url: null,
    git_ssh_url: "git@example.com:jsmith/example.git",
    git_http_url: "http://example.com/jsmith/example.git",
    namespace: "Jsmith",
    visibility_level: 0,
    path_with_namespace: "jsmith/example",
    default_branch: "master",
    homepage: "http://example.com/jsmith/example",
    url: "git@example.com:jsmith/example.git",
    ssh_url: "git@example.com:jsmith/example.git",
    http_url: "http://example.com/jsmith/example.git",
  },
  repository: {
    name: "Example",
    url: "ssh://git@example.com/jsmith/example.git",
    description: "",
    homepage: "http://example.com/jsmith/example",
    git_http_url: "http://example.com/jsmith/example.git",
    git_ssh_url: "git@example.com:jsmith/example.git",
    visibility_level: 0,
  },
  commits: [],
  total_commits_count: 0,
};
