version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6688:6688"
    environment:
      - PORT=6688
      - TEMPLATE=default
    command: ["npm", "start"]